trigger:
- main

parameters:
- name: agentPool
  displayName: 'Pool de agentes'
  type: string
  default: pool_de_agentes
  values:
  - pool_de_agentes
  - eduardino

jobs:
- job: EjecutarControladorDino
  pool:
    name: ${{ parameters.agentPool }}

  steps:
  - checkout: self
    clean: true
    displayName: 'Descargar Código del Repositorio'

  - script: |
      pip install selenium
      pip install webdriver-manager
    displayName: 'Instalar Librerías de Python'



  - script: |
      python controlador_dino.py
    displayName: 'Ejecutar controlador_dino.py en GUI Real'


