trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    pip install selenium webdriver-manager
    python controlador_dino.py
  displayName: 'Ejecutar Bot en Azure'