trigger:
- main

pool:
  vmImage: 'windows-latest' # para pruebas UI

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install selenium webdriver-manager
  displayName: 'Instalar dependencias de Selenium'

- script: |
    python controlador_dino.py
  displayName: 'Ejecutar script de Selenium'

    
